inputs:
  project:
    description: GCP project id
    required: true
  region:
    description: GCP region
    required: false
    default: asia-northeast1
  verbosity:
    description: "Cloud Run deploy command verbosity (possible values: debug, info, warning, error, critical, none)"
    required: false
    default: warning
  service:
    description: Cloud Run service name
    required: true
  repository:
    description: GCP Artifact Registry repository
    required: false
    default: cloud-run-source-deploy
  image:
    description: image name
    required: true
  image_tag:
    description: image tag
    required: false
    default: latest
  workload_identity_provider:
    description: Workload Identity Provider
    required: true
  service_account:
    description: Service Account
    required: true
  dockerfile:
    description: "if you provide Dockerfile path, build with build-push-action. otherwise use buildpacks"
    default: ''
    required: false
  context:
    description: "docker context for build-push-action"
    default: '.'
    required: false
  build-args:
    description: build-args for build-push-action
    default: ''
    required: false
  driver:
    description: driver for setup-buildx-action
    default: docker-container
    required: false

outputs:
  url:
    description: CloudRun URL
    value: ${{ steps.get-cloudrun-url.outputs.URL }}

name: Deploy CloudRun
description: Deploy CloudRun
runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@6a7c903a70c8625ed6700fa299f5ddb4ca6022e9 # v2.1.5

    - name: Login to GAR
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ inputs.region }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Set up Docker Buildx
      if: inputs.dockerfile != ''
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      with:
        driver: ${{ inputs.driver }}

    - name: Cache Docker layers
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      if: inputs.dockerfile != ''
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.service }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.service }}-

    - name: Build and push image
      if: inputs.dockerfile != ''
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.region }}-docker.pkg.dev/${{ inputs.project }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.image_tag }}
        platforms: linux/amd64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        build-args: ${{ inputs.build-args }}

    - name: Move cache
      if: inputs.dockerfile != ''
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        ls /tmp/.buildx-cache

    # Buildpack is slow https://github.com/buildpacks/pack
    - name: Install Pack CLI
      if: inputs.dockerfile == ''
      uses: buildpacks/github-actions/setup-pack@8203df0b7ac31e358daa391b1949da5650e7f4f0 # v5.9.3

    - name: Build app with pack CLI using Buildpack Cache image (see https://buildpacks.io/docs/app-developer-guide/using-cache-image/) & publish to Docker Hub
      if: inputs.dockerfile == ''
      shell: bash
      run: |
        pack build "${{ inputs.region }}-docker.pkg.dev/${{ inputs.project }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.image_tag }}" \
            --tag "${{ inputs.region }}-docker.pkg.dev/${{ inputs.project }}/${{ inputs.repository }}/${{ inputs.image }}:latest" \
            --path . \
            --builder heroku/builder:22 \
            --cache-image "${{ inputs.region }}-docker.pkg.dev/${{ inputs.project }}/${{ inputs.repository }}/${{ inputs.image }}-cache:latest" \
            --publish

    - name: Deploy CloudRun
      shell: bash
      run: |
        gcloud run deploy ${{ inputs.service }} \
            --image "${{ inputs.region }}-docker.pkg.dev/${{ inputs.project }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.image_tag }}" \
            --project "${{ inputs.project }}" \
            --region "${{ inputs.region }}" \
            --verbosity "${{ inputs.verbosity }}"

    - name: Get CloudRun URL
      shell: bash
      id: get-cloudrun-url
      run: |
        set -o pipefail
        echo "URL=$(gcloud run services describe ${{ inputs.service }} --project "${{ inputs.project }}" --region "${{ inputs.region }}" --format json | jq -r .status.url)" >> "$GITHUB_OUTPUT"
