name: LLM PR Reviewer - Multi Provider

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-openai:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: OpenAI Review
        uses: ./llm-pr-reviewer
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          llm-provider: openai
          model: gpt-4

  review-anthropic:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Anthropic Review
        uses: ./llm-pr-reviewer
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          llm-provider: anthropic
          model: claude-3-sonnet