name: 'Action Required Reminder'
description: 'Check for unreplied Slack messages and unreviewed GitHub PRs, then send a reminder to Slack'
author: 'nakamasato'

inputs:
  gh_org:
    description: 'Target GitHub organization. If not specified with gh_repos, all repos will be checked'
    required: false
  gh_repos:
    description: 'Target GitHub repositories (comma-separated). If specified, gh_org will be ignored'
    required: false
  slack_workspace:
    description: 'Slack workspace name (subdomain part of your Slack URL)'
    required: true
  slack_channel_id:
    description: 'Slack channel ID for posting reminders'
    required: true
  slack_bot_token:
    description: 'Slack Bot Token for posting messages (optional, uses slack_user_token if not provided)'
    required: false
  slack_user_token:
    description: 'Slack User Token for searching messages (required)'
    required: true
  slack_search_days:
    description: 'Number of days to search for Slack messages'
    required: false
    default: '3'
  slack_user_id:
    description: 'Target Slack user ID to check for unreplied messages'
    required: true
  github_user:
    description: 'GitHub username for PR review requests (e.g., username)'
    required: true
  github_token:
    description: 'GitHub Token for repository access'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Check unreplied Slack messages
      id: check-slack
      shell: bash
      env:
        SLACK_USER_TOKEN: ${{ inputs.slack_user_token }}
        SLACK_WORKSPACE: ${{ inputs.slack_workspace }}
        SLACK_USER_ID: ${{ inputs.slack_user_id }}
        SLACK_SEARCH_DAYS: ${{ inputs.slack_search_days }}
      run: |
        # Output logs to stderr and capture only URLs from stdout
        echo "Running Slack message check..."
        SLACK_URLS=$("$GITHUB_ACTION_PATH/check_not_replied_slack_message.sh")

        # Save output in JSON format
        echo "urls<<EOF" >> "$GITHUB_OUTPUT"
        echo "$SLACK_URLS" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        # Count number of messages
        COUNT=$(echo "$SLACK_URLS" | jq 'length')
        echo "count=$COUNT" >> "$GITHUB_OUTPUT"

    - name: Check unreviewed GitHub PRs
      id: check-prs
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GH_ORG: ${{ inputs.gh_org }}
        GH_REPOS: ${{ inputs.gh_repos }}
        GH_USER: ${{ inputs.github_user }}
      run: |
        echo "Running GitHub PR check..."
        PR_URLS=$("$GITHUB_ACTION_PATH/check_not_reviewed_gh_pr.sh")

        # Save output in JSON format
        echo "urls<<EOF" >> "$GITHUB_OUTPUT"
        echo "$PR_URLS" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        # Count number of PRs
        COUNT=$(echo "$PR_URLS" | jq 'length')
        echo "count=$COUNT" >> "$GITHUB_OUTPUT"

    - name: Build Slack message blocks
      id: build-message
      shell: bash
      env:
        SLACK_COUNT: ${{ steps.check-slack.outputs.count }}
        SLACK_URLS: ${{ steps.check-slack.outputs.urls }}
        PR_COUNT: ${{ steps.check-prs.outputs.count }}
        PR_URLS: ${{ steps.check-prs.outputs.urls }}
      run: |
        # Build header block
        BLOCKS='[
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "👋 This is action required reminder!"
            }
          }
        ]'

        # Add Slack messages section if any
        if [ "$SLACK_COUNT" -gt 0 ]; then
          SLACK_SECTION='{
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "📬 *Unreplied Slack messages: '$SLACK_COUNT' messages*"
            }
          }'
          BLOCKS=$(echo "$BLOCKS" | jq ". += [$SLACK_SECTION]")

          # Build Slack links list
          SLACK_LINKS=$(echo "$SLACK_URLS" | jq -r '.[] | "• <" + .url + "|" + (.title | gsub("[<>|]"; "")) + ">"' | tr '\n' '\n')
          if [ -n "$SLACK_LINKS" ]; then
            SLACK_LINKS_SECTION='{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "'"$SLACK_LINKS"'"
              }
            }'
            BLOCKS=$(echo "$BLOCKS" | jq ". += [$SLACK_LINKS_SECTION]")
          fi
        fi

        # Add PR section if any
        if [ "$PR_COUNT" -gt 0 ]; then
          PR_SECTION='{
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "🔍 *Review Requested PR: '$PR_COUNT' PRs*"
            }
          }'
          BLOCKS=$(echo "$BLOCKS" | jq ". += [$PR_SECTION]")

          # Build PR links list
          PR_LINKS=$(echo "$PR_URLS" | jq -r '.[] | "• <" + .url + "|" + (.title | gsub("[<>|]"; "")) + ">"' | tr '\n' '\n')
          if [ -n "$PR_LINKS" ]; then
            PR_LINKS_SECTION='{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "'"$PR_LINKS"'"
              }
            }'
            BLOCKS=$(echo "$BLOCKS" | jq ". += [$PR_LINKS_SECTION]")
          fi
        fi

        # Add footer
        if [ "$SLACK_COUNT" -eq 0 ] && [ "$PR_COUNT" -eq 0 ]; then
          FOOTER_TEXT="✨ Awesome! No action required!"
        else
          FOOTER_TEXT="Keep it up!💪"
        fi

        FOOTER_SECTION='{
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": "'$FOOTER_TEXT'"
          }
        }'
        BLOCKS=$(echo "$BLOCKS" | jq ". += [$FOOTER_SECTION]")

        # Save blocks to output
        echo "blocks<<EOF" >> "$GITHUB_OUTPUT"
        echo "$BLOCKS" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Post reminder to Slack
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token || inputs.slack_user_token }}
        payload: |
          channel: ${{ inputs.slack_channel_id }}
          text: "Action required reminder"
          blocks: ${{ steps.build-message.outputs.blocks }}

branding:
  icon: 'check-circle'
  color: 'green'
