name: 'LLM PR Reviewer'
description: 'Automatically reviews PRs and provides improvement suggestions as comments using an LLM'
author: 'Naka Masato'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  llm_provider:
    description: 'LLM provider to use (openai or anthropic)'
    default: 'openai'
    required: false
  openai_api_key:
    description: 'OpenAI API key (required if using OpenAI)'
    required: false
  openai_model:
    description: 'OpenAI model'
    default: 'gpt-4-turbo-preview'
    required: false
  anthropic_api_key:
    description: 'Anthropic API key (required if using Anthropic)'
    required: false
  anthropic_model:
    description: 'Anthropic model'
    default: 'claude-3-opus-20240229'
    required: false
  file_extensions:
    description: 'File extensions to review (comma-separated)'
    default: '.js,.ts,.jsx,.tsx,.py,.java,.go,.rb,.php,.cs'
    required: false
  max_comments:
    description: 'Maximum number of comments per PR'
    default: '10'
    required: false
  exclude_patterns:
    description: 'File patterns to exclude (comma-separated glob patterns)'
    default: 'node_modules/**,dist/**,build/**,**/*.min.js'
    required: false
  debug:
    description: 'Debug mode. If true, the bot will delete its own comments before posting new ones. The bot will also print debug information to the comments.'
    default: 'false'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout github actions repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: nakamasato/github-actions

    - name: Set up Python
      uses: nakamasato/github-actions/setup-poetry@main
      with:
        python-version-file: llm-pr-reviewer/pyproject.toml
        working-directory: llm-pr-reviewer

    - name: install
      shell: bash
      run: poetry install

    # TODO: if there's need to configure any args for checkout
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run PR Review
      run: poetry run python ${{ github.action_path }}/pr_reviewer.py
      shell: bash
      working-directory: llm-pr-reviewer
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        LLM_PROVIDER: ${{ inputs.llm_provider }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        OPENAI_MODEL: ${{ inputs.openai_model }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        ANTHROPIC_MODEL: ${{ inputs.anthropic_model }}
        FILE_EXTENSIONS: ${{ inputs.file_extensions }}
        MAX_COMMENTS: ${{ inputs.max_comments }}
        EXCLUDE_PATTERNS: ${{ inputs.exclude_patterns }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
        DEBUG: ${{ inputs.debug }}
