name: llm-pr-reviewer

on:
  pull_request:
    branches: [ main ]

jobs:
  review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: llm-pr-reviewer
        uses: ./llm-pr-reviewer
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          debug: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Poetry
        uses: ./setup-poetry
        with:
          working-directory: llm-pr-reviewer
      - name: Run tests
        working-directory: llm-pr-reviewer
        run: poetry run pytest
