name: llm-pr-reviewer

on:
  pull_request:
    branches: [ main ]

jobs:
  permissions:
    contents: read
    pull_request: write
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nakamasato/github-actions/llm-pr-reviewer@llm-pr-reviewer
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
