name: monthly-project-summary-slack

on:
  workflow_call:
    inputs:
      yearmonth:
        description: 'Target year-month (YYYY-MM format). If not specified, uses last month'
        required: false
        type: string
      slack_channel:
        description: 'Slack channel ID for posting results'
        required: true
        type: string
      timeout_minutes:
        description: 'Timeout in minutes for Claude Code execution'
        required: false
        type: number
        default: 5
    secrets:
      slack_bot_token:
        description: 'Slack Bot Token'
        required: true
      slack_team_id:
        description: 'Slack Team ID'
        required: true
      claude_code_oauth_token:
        description: 'Claude Code OAuth Token'
        required: false
      anthropic_api_key:
        description: 'Anthropic API Key'
        required: false

jobs:
  generate-monthly-summary:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate monthly project summary
        uses: nakamasato/github-actions/monthly-project-summary-slack@add-composite-action-monthly-summary # TODO: Replace with tag after release
        with:
          yearmonth: ${{ inputs.yearmonth }}
          slack_channel: ${{ inputs.slack_channel }}
          timeout_minutes: ${{ inputs.timeout_minutes }}
          slack_bot_token: ${{ secrets.slack_bot_token }}
          slack_team_id: ${{ secrets.slack_team_id }}
          claude_code_oauth_token: ${{ secrets.claude_code_oauth_token }}
          anthropic_api_key: ${{ secrets.anthropic_api_key }}
